## Practice with NumPy numerical programming
This practice covers some of the most important aspects of creating and manipulating arrays using the numpy library.

## Level 1

### Exercise 1

In [1]:
# A simple Python library for easily displaying tabular data in a visually appealing ASCII table format.
from prettytable import PrettyTable

# Import numpy library using the alias *np*
import numpy as np 

In [2]:
# Define a function called 'summaryArray()'
# This function creates a basic statistical summary of the data contained in a 1D-array. 
# If the array has more than one dimension, it displays an error message.

def summaryArray(array):
    summary = PrettyTable()
    summary.field_names = ["Description", "Value"]
    if array.ndim >1:
        print('Error!, array dimension is greater than 1')
    else:
        summary.add_row(["Minimun",np.amin(array)])  # Minimum value of the element along a specified axis.    
        summary.add_row(["Maximum",np.amax(array)])  # Maximum value of the element along a specified axis.
        summary.add_row(["Mean",np.mean(array)])     # Mean value of the data set.
        summary.add_row(["Median",np.median(array)]) # Median value of the data set.
        summary.add_row(["Std Dev",np.std(array)])   # It determines the standard deviation.
        summary.add_row(["variance",np.var(array)])  # It determines the variance.
        summary.add_row(["Range",np.ptp(array)])     # It returns a range of values along an axis.
        summary.add_row(["Average",np.average(array)]) # It determines the weighted average.
        summary.add_row(["Percentile",np.percentile(array,10,0)]) #It determines the nth percentile of data along the specified axis.
        print(summary)

In [3]:
# Validation 1
x = np.array([1,2,3,4,5,6,7,8,9])
summaryArray(x)

+-------------+-------------------+
| Description |       Value       |
+-------------+-------------------+
|   Minimun   |         1         |
|   Maximum   |         9         |
|     Mean    |        5.0        |
|    Median   |        5.0        |
|   Std Dev   | 2.581988897471611 |
|   variance  | 6.666666666666667 |
|    Range    |         8         |
|   Average   |        5.0        |
|  Percentile |        1.8        |
+-------------+-------------------+


In [4]:
# Validation 2
y = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(y.ndim)
summaryArray(y)

2
Error!, array dimension is greater than 1


### Exercise 2

In [5]:
## Import 'random' library fron numpy. This allows to use the rand() method to specify the shape of the array
from numpy import random 

In [6]:
# Definition of a function that generates an NxN square array of random numbers between 0 and 100.

def randomNxN(N):
    array2 = np.random.rand(N,N)
    return(array2)

In [7]:
# validation 1
randomNxN(3)

array([[0.322107  , 0.90499433, 0.72395276],
       [0.88913248, 0.36220304, 0.42793481],
       [0.72835118, 0.0698369 , 0.20057544]])

### Exercise 3

In [8]:
# Definition of a function that calculates the totals per row and the totals per column from a two-dimensional array

def totalArray(arr):
    # argument validation
    if arr.shape == (2,2):
        axis0 = np.sum(arr,axis=0) # sum of the column elements has been calculated
        axis1 = np.sum(arr,axis=1) # sum of the row elements has been calculated
        print('The sum of the column elements in the array is ', axis0 )
        print('The sum of the row elements in the array is ', axis1 )
    else:
        print("Error!, the array dimension is different from 2")        

In [9]:
# Generate a 2-D array containing random integers from 0 to 10
array3 = random.randint(10, size=(2, 2))
array3

array([[8, 6],
       [3, 1]])

In [10]:
# Validation
totalArray(array3)

The sum of the column elements in the array is  [11  7]
The sum of the row elements in the array is  [14  4]


### Exercise 4

In [11]:
# This function manually calculates the correlation coefficient using np.cov methode.
# The argument is a 2D-array with the X and Y variables 

def corrCoefPearson(arr2):
    rho = np.cov(arr2)[0][1]/(np.cov(arr2)[0][0]*np.cov(arr2)[1][1])**(0.5)
    return(rho)

#### Validation

In [12]:
# creating an array with the specific format
x = [43,21,25,42,57,59]
y = [99,65,79,75,87,81]
X = np.stack((x, y), axis=0)
X


array([[43, 21, 25, 42, 57, 59],
       [99, 65, 79, 75, 87, 81]])

In [13]:
# Execute function
corrCoefPearson(X)

0.5298089018901744

In [14]:
np.corrcoef(X)

array([[1.       , 0.5298089],
       [0.5298089, 1.       ]])